import type { Metadata } from "next";
import "./globals.css";
import { bungee, inter } from "./_ui/components/fonts";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${bungee.variable} font-inter bg-[#010102] text-white antialiased`}
      >
        <div className="flex h-screen">
          <div className="flex flex-col justify-center p-8">{children}</div>
          <div className="flex-1">
            <Image
              src="/auth-bg.jpg"
              alt="Login Illustration"
              width={1920}
              height={1080}
              className="h-full object-contain"
            />
          </div>
        </div>
      </body>
    </html>
  );
}
